# Social-Cognitive Perspective (SCP) - Dynamic Learning
# Emphasizes adaptive self-concepts and observational learning

model_name: "SCP_Dynamic"
description: >
  Tests dynamic leadership emergence through observational learning
  and adaptive self-concepts. Agents learn from both direct
  interactions and observed behaviors.
theoretical_basis: "Social-Cognitive Perspective (Bandura, 1986)"

inherits:
  - "../base.yaml::defaults"
  - "../base.yaml::theoretical_bases.scp"

parameters:
  agent_properties:
    schemas:
      social_identity_influence: 0.1
    self_schema:
      separate: true  # Distinct self-schemas
    identity_representation:
      leader_identity:
        update_rule: "dynamic_feedback"
      follower_identity:
        update_rule: "dynamic_feedback"

  interaction_rules:
    claim_decision_rule: "self_attributes > schema"
    grant_decision_rule: "other_attributes > schema"
    memory_length: 10  # Longer memory for learning

  simulation_properties:
    time_points: 150  # Longer simulation for learning effects
    replication_count: 20
    outcome_metrics:
      - "time_to_stability"
      - "learning_rate"
      - "behavioral_consistency"

validation:
  expected_outcomes:
    - "Gradual identity development"
    - "Behavioral adaptation over time"
    - "Learning from observed interactions"
  metrics_thresholds:
    learning_rate: ">= 0.3"
    behavioral_consistency: ">= 0.6"
    time_to_stability: "between 50 and 100" 