# Social-Interactionist Perspective (SIP) - Hierarchical Leadership
# Based on traditional hierarchical leadership structure with static ILTs

model_name: "SIP_Hierarchical"
description: >
  Tests hierarchical leadership structure schema (LSS) with static ILTs.
  Minimal social identity influence promotes single-leader emergence.
theoretical_basis: "Social-Interactionist Perspective (DeRue & Ashford, 2010)"

inherits:
  - "../base.yaml::defaults"
  - "../base.yaml::theoretical_bases.sip"

parameters:
  # Override only the parameters that differ from base
  agent_properties:
    schemas:
      social_identity_influence: 0.0  # Minimal influence promotes hierarchy

  interaction_rules:
    claim_decision_rule: "self_attributes > schema"
    grant_decision_rule: "other_attributes > schema"
    memory_length: 0  # No memory effects

  simulation_properties:
    outcome_metrics:
      - "identity_stabilization"
      - "variance_reduction"
      - "hierarchical_emergence"

validation:
  expected_outcomes:
    - "Strong hierarchical structure emergence"
    - "Clear leader-follower role differentiation"
    - "Stable leadership identities"
  metrics_thresholds:
    hierarchical_emergence: ">= 0.7"
    identity_stabilization: "<= 20 timesteps"
    variance_reduction: ">= 0.8" 